gems:
  - jekyll-seo-tag

port: 4001

styles:
  - //fonts.googleapis.com/css?family=Open+Sans:300,400,700
  - /sjt/assets/css/main.css

javascript:
  - /sjt/assets/js/main.js

markdown: kramdown

title:        Simple Jekyll Theme
tagline:      Short Description
baseurl: /sjt

author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/

buttons:
  -
    name: View on GitHub
    link: https://github.com/kosatyi/sjt
  -
    name: Download .zip
    link: http://github.com/kosatyi/sjt/archive/master.zip
  -
    name: Download .tar.gz
    link: http://github.com/kosatyi/sjt/archive/master.tar.gz

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default