plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

port: 4004

exclude:
  - vendor
  - node_modules
  - src

navigation: true
projects: true

baseurl: /sjt

brand: SJT
title: Simple Jekyll Theme
description: Yet another one jekyyl theme for github projects
logo: icons/github.svg
styles:
  - https://fonts.googleapis.com/css?family=Ubuntu:400,400i,500,500i

adsense: ca-pub-3650650669153101

author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/

toolbar:
-
  name: Docs
  link: /docs/
-
  name: Examples
  link: /examples/