plugins:
  - jekyll-seo-tag

port: 4002

baseurl: /sjt

navigation: true

brand: SJT
title: Simple Jekyll Theme
description: Yet another one jekyyl theme for github projects

author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/

toolbar:
-
  name: Docs
  link: /docs/
-
  name: Examples
  link: /examples/