plugins:
  - jekyll-seo-tag

port: 4001

styles:

javascript:

baseurl:

author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/

toolbar:
-
  name: Docs
  link: /docs/
-
  name: Examples
  link: /examples/