plugins:
  - jekyll-seo-tag

port: 4003

baseurl: /sjt

navigation: true
projects: true

brand: SJT
title: Simple Jekyll Theme
description: Yet another one jekyyl theme for github projects

styles:
  - https://fonts.googleapis.com/css?family=Ubuntu:400,400i,500,500i


author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/

toolbar:
-
  name: Docs
  link: /docs/
-
  name: Examples
  link: /examples/