gems:
  - jekyll-seo-tag

markdown: kramdown

title:        Simple Jekyll Theme
tagline:      Short Description
baseurl:

author:
  name:
  url:

buttons:
  github:
  zip:
  tar:

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default