gems:
  - jekyll-seo-tag

port: 4001


baseurl: /sjt

styles:
  - main.css
javascript:
  - main.js

markdown: kramdown

title:        Simple Jekyll Theme
tagline:      Short Description
baseurl:

author:
  name:
  url:

buttons:
  -
    name: View on GitHub
    link:
  -
    name: Download .zip
    link:
  -
    name: Download .tar.gz
    link:

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default