gems:
  - jekyll-seo-tag

port: 4001


baseurl: /sjt

styles:
  - /assets/css/main.css

additional_styles:
  - https://fonts.googleapis.com/css?family=Open+Sans:300,400,700

javascript:
  - /assets/js/main.js

markdown: kramdown

title:        Simple Jekyll Theme
tagline:      Short Description
baseurl:

author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/

buttons:
  -
    name: View on GitHub
    link: https://github.com/kosatyi/sjt
  -
    name: Download .zip
    link: http://github.com/kosatyi/sjt/archive/master.zip
  -
    name: Download .tar.gz
    link: http://github.com/kosatyi/sjt/archive/master.tar.gz

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default